dist: trusty
sudo: required
language: node_js
env:
- CXX=g++-4.8
node_js:
  - 6
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - mysql-server-5.6
        - mysql-client-core-5.6
        - mysql-client-5.6

before_install:
    - $CXX --version
    - case ${TRAVIS_NODE_VERSION} in 0.8*|0.10*) npm install -g npm@2 ;; esac
before_script:
  - mkdir build
  - mysql -u root -e 'create database database_test'
  - mysql -u root -e "GRANT ALL PRIVILEGES ON database_test.* TO 'root'@'localhost' WITH GRANT OPTION;"
  - npm run build
  - npm run migrate:test
  - npm run seed:test
