language: node_js
env:
- CXX=g++-4.8
node_js:
  - 6
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
sudo: false
services:
    - mysql

before_install:
    - $CXX --version
    - case ${TRAVIS_NODE_VERSION} in 0.8*|0.10*) npm install -g npm@2 ;; esac
before_script:
  - mysql -e 'create database database_test'
  - npm install -g gulp
  - npm run build
  - npm run install
  - npm run prepare_travis
