language: node_js
services:
  - mysql
env:
- CXX=g++-4.8
node_js:
  - 6
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8

before_install:
    - $CXX --version
    - case ${TRAVIS_NODE_VERSION} in 0.8*|0.10*) npm install -g npm@2 ;; esac
before_script:
  - mkdir build
  - mysql -u root -e 'create database database_test'
  - npm run build
  - npm run migrate:test
  - npm run seed:test
